<a href="https://colab.research.google.com/github/LoopyMekanic/Analysis/blob/Trying-to-learn/Numpy_2_Python_Data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [11]:
# Slicing NumPy Arrays - Return 2,3,4,5| Slice 1:5 returns 1 up till 5 but not including 5
np1 = np.array(["Tony", "Tim", "Mary", "Bob", "Pete", "April", "Wes", "Steve", "Aspen", "Ivy"])
print(np1[1:5])
np2 = np1[1:5]
print(np2)

['Tim' 'Mary' 'Bob' 'Pete']
['Tim' 'Mary' 'Bob' 'Pete']


In [12]:
# Return from something till end of array
print(np1[3:]) # : nothing means till the end

['Bob' 'Pete' 'April' 'Wes' 'Steve' 'Aspen' 'Ivy']


In [13]:
# Return negative slices, from the end backwards
print(np1[-3:-1]) # -1 is up till but not including -1

['Steve' 'Aspen']


In [15]:
# Slices with steps
print(np1[1:5])
print(np1[1:5:2])


['Tim' 'Mary' 'Bob' 'Pete']
['Tim' 'Bob']


In [17]:
# Slices whole thing in steps
print(np1)
print(np1[::2])

['Tony' 'Tim' 'Mary' 'Bob' 'Pete' 'April' 'Wes' 'Steve' 'Aspen' 'Ivy']
['Tony' 'Mary' 'Pete' 'Wes' 'Aspen']


In [18]:
# Slice a 2-d array
np2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(np2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [19]:
# Pull out a single item '8'
print(np2[1,2])

8


In [20]:
# Pull slices from 1-dimension
print(np2[0:1,1:3]) # Row, Item

[[2 3]]


In [21]:
# Pull slices from both dimensions (2,3 and 7,8)
print(np2[0:2,1:3]) # Row, Item

[[2 3]
 [7 8]]
