<a href="https://colab.research.google.com/github/LoopyMekanic/Analysis/blob/Trying-to-learn/Numpy_9_Filtering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
# Filter Arrays with Boolean Index List
np1 = np.array([1,2,3,4,5,6,7,8,9,10])

In [4]:
# Filter Out The First two Items
x = [True, True, False, False, False, False, False, False, False, False]
print(np1[x])

[1 2]


In [10]:
# Filtered Lists
filtered = []
for item in np1:
  if item % 2 == 0:
    filtered.append(True)
  else:
    filtered.append(False)

print(np1)
print(filtered)
print(np1[filtered])

[ 1  2  3  4  5  6  7  8  9 10]
[False, True, False, True, False, True, False, True, False, True]
[ 2  4  6  8 10]


In [11]:
# Use any logic
filtered = []
for item in np1:
  if item > 5:
    filtered.append(True)
  else:
    filtered.append(False)

print(np1)
print(filtered)
print(np1[filtered])

[ 1  2  3  4  5  6  7  8  9 10]
[False, False, False, False, False, True, True, True, True, True]
[ 6  7  8  9 10]


In [12]:
# Use Shorthand
filtered = np1 % 2 == 1
print(np1[filtered])

[1 3 5 7 9]
