<a href="https://colab.research.google.com/github/LoopyMekanic/Analysis/blob/Trying-to-learn/Numpy_5_Shape_and_Reshape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# Create 1-D Array and Get Shape
np1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(np1.shape)

(12,)


In [8]:
# Create 2-D Array and Get Shape (returls rows/column-elements)
np2 = np.array([[1,2,3,4,5,6], [7,8,9,10,11,12]])
print(np2.shape)
print(np2)

(2, 6)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [9]:
# Reshape 1-D Arry into a 2-D Array
np3 = np1.reshape(3, 4)
print(np3)
print(np3.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [5]:
# Reshape 3-D Array


In [6]:
# Flatten to 1-D
