<a href="https://colab.research.google.com/github/LoopyMekanic/Analysis/blob/Trying-to-learn/Numpy_3_Universal_Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
np1 = np.array([-3,-2,-1,0,1,2,3,4,5,6,7,8,9])
print(np1)

[-3 -2 -1  0  1  2  3  4  5  6  7  8  9]


In [ ]:
# Square Root
print(np.sqrt(np1))

[       nan        nan        nan 0.         1.         1.41421356
 1.73205081 2.         2.23606798 2.44948974 2.64575131 2.82842712
 3.        ]


/tmp/ipython-input-1725249946.py:2: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(np1))


In [ ]:
# Absolute Value
np.absolute(np1)

array([3, 2, 1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Exponential
np.exp(np1)

array([4.97870684e-02, 1.35335283e-01, 3.67879441e-01, 1.00000000e+00,
       2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [ ]:
# Min/Max
print(np1)
#Min
#np.min(np1)
print(np.max(np1))

[-3 -2 -1  0  1  2  3  4  5  6  7  8  9]
9


In [ ]:
# Positive/Negative -1 = negative, 1 = positive
print(np.sign(np1))

[-1 -1 -1  0  1  1  1  1  1  1  1  1  1]


In [ ]:
# Trig functions - Sin, Cos, Log
print(np.sin(np1))
print(np.cos(np1))
print(np.tan(np1))
print(np.log(np1))

[-0.14112001 -0.90929743 -0.84147098  0.          0.84147098  0.90929743
  0.14112001 -0.7568025  -0.95892427 -0.2794155   0.6569866   0.98935825
  0.41211849]
[-0.9899925  -0.41614684  0.54030231  1.          0.54030231 -0.41614684
 -0.9899925  -0.65364362  0.28366219  0.96017029  0.75390225 -0.14550003
 -0.91113026]
[ 0.14254654  2.18503986 -1.55740772  0.          1.55740772 -2.18503986
 -0.14254654  1.15782128 -3.38051501 -0.29100619  0.87144798 -6.79971146
 -0.45231566]
[       nan        nan        nan       -inf 0.         0.69314718
 1.09861229 1.38629436 1.60943791 1.79175947 1.94591015 2.07944154
 2.19722458]


/tmp/ipython-input-744596335.py:5: RuntimeWarning: divide by zero encountered in log
  print(np.log(np1))
/tmp/ipython-input-744596335.py:5: RuntimeWarning: invalid value encountered in log
  print(np.log(np1))


In [ ]:
# Master List
# https://numpy.org/doc/stable/reference/ufuncs.html