<a href="https://colab.research.google.com/github/LoopyMekanic/Analysis/blob/Trying-to-learn/Pandas_2_DataFrames.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
# Import Pandas
import pandas as pd
import numpy as np
from numpy.random import rand

In [8]:
# Create Random data
my_data = rand(4,3) # Rows/Colums
print(my_data)

[[0.35004414 0.96085086 0.58087688]
 [0.90074513 0.13966124 0.23642262]
 [0.03236653 0.97193224 0.24863689]
 [0.19637818 0.84490233 0.64934012]]


In [9]:
# Create headers
my_rows = ["A", "B", "C", "D"]
my_cols = ["Monday", "Tuesday", "Friday"]

In [10]:
# Create our DataFrame!!
my_df = pd.DataFrame(my_data, my_rows, my_cols)

In [11]:
# print
print(my_df)

     Monday   Tuesday    Friday
A  0.350044  0.960851  0.580877
B  0.900745  0.139661  0.236423
C  0.032367  0.971932  0.248637
D  0.196378  0.844902  0.649340


In [14]:
# Print with formatting
my_df

,Monday,Tuesday,Friday
A,0.350044,0.960851,0.580877
B,0.900745,0.139661,0.236423
C,0.032367,0.971932,0.248637
D,0.196378,0.844902,0.649340
