In [5]:
# Python list
my_list = [1, 2, 3, 4, 5, "Tony", True]
my_list2 = [6,7,8, my_list]

In [6]:
# Import Numpy
import numpy as np

In [7]:
# Create a numpy array
np1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(np1)
print(np1[2])

[0 1 2 3 4 5 6 7 8 9]
2


In [8]:
# Shape - shows the number of elements in the array like the python len function
print(np1.shape)

(10,)


In [9]:
# Arange
np2 = np.arange(10)
print(np2)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
# Step
np3 = np.arange(0,12,2)
print(np3)

[ 0  2  4  6  8 10]


In [16]:
# Zeros
np4 = np.zeros(10)
print(np4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [12]:
# Multi-Dimensional Arrays with Zeros

In [13]:
# Full

In [14]:
# Multi-Dimensional Arrays with Full

In [15]:
# Covert Python List to Numpy Array